export const site = {
  name: "VNM Telecommunications",
  legalName: "VNM TELECOMMUNICATIONS LLP",
  tagline: "Smartphones & electronics for trade.",
  description: "A Pune-based Indian merchant exporter and B2B wholesaler of smartphones, consumer electronics and accessories—serving domestic distribution and international trade partners.",
  email: "Support@vnmtelecom.in",
  phone: "9999999999",
  whatsapp: "9999999999",
  address: "North Blocke-304/5/6 Sacred World Mall, Third floor, Above Kwality Restaurant, Near Jagtap Chowk, Wanowrie, Pune 411040",
  hqCity: "Pune",
  hqCountry: "India",
  countriesServed: "50+",
  productCategories: "100+",
  annualUnits: "500K+",
  dispatchTime: "48h",
  url: "https://vnmtelecom.in",
};
