export const site = {
  name: "VNM Telecommunications",
  legalName: "VNM TELECOMMUNICATIONS LLP",
  tagline: "Smartphones & electronics for trade.",
  description:
    "VNM Telecommunications LLP is a Pune-based Indian merchant exporter and B2B wholesaler of smartphones, consumer electronics and accessories. We supply distributors, wholesalers and bulk traders across India and export markets.",
  shortDescription:
    "Pune B2B wholesale & merchant export of smartphones, consumer electronics and accessories.",
  email: "Support@vnmtelecom.in",
  phone: "9999999999",
  phoneE164: "+919999999999",
  whatsapp: "9999999999",
  address: "North Blocke-304/5/6 Sacred World Mall, Third floor, Above Kwality Restaurant, Near Jagtap Chowk, Wanowrie, Pune 411040",
  streetAddress: "North Blocke-304/5/6 Sacred World Mall, Third floor, Above Kwality Restaurant, Near Jagtap Chowk, Wanowrie",
  hqCity: "Pune",
  hqRegion: "Maharashtra",
  postalCode: "411040",
  hqCountry: "India",
  countryCode: "IN",
  countriesServed: "50+",
  productCategories: "100+",
  annualUnits: "500K+",
  dispatchTime: "48h",
  url: "https://vnmtelecom.in",
  locale: "en_IN",
  keywords: [
    "VNM Telecommunications",
    "VNM TELECOMMUNICATIONS LLP",
    "smartphone wholesale India",
    "mobile phone exporter Pune",
    "B2B mobile wholesale",
    "merchant exporter smartphones",
    "consumer electronics wholesale Pune",
    "refurbished phone wholesale India",
    "mobile accessories bulk supplier",
    "electronics distributor Maharashtra",
    "smartphone export India",
    "Wanowrie Pune telecom wholesale",
  ],
};
